[0m23:52:37.280755 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27eccb1070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27ebe2fa60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27ebe2fac0>]}


============================== 23:52:37.293161 | 007e169f-ab1a-41f5-b2e9-95e9e62e8f7b ==============================
[0m23:52:37.293161 [info ] [MainThread]: Running with dbt=1.9.4
[0m23:52:37.295203 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models staging+', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:52:37.298008 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/subscription-misuse-detection/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:52:37.300669 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.11177311, "process_in_blocks": "0", "process_kernel_time": 0.140177, "process_mem_max_rss": "91136", "process_out_blocks": "0", "process_user_time": 2.282893}
[0m23:52:37.302750 [debug] [MainThread]: Command `dbt run` failed at 23:52:37.302413 after 0.11 seconds
[0m23:52:37.304457 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27eccb1070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27ebe73df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27ebe730d0>]}
[0m23:52:37.306122 [debug] [MainThread]: Flushing usage events
[0m23:52:37.981650 [debug] [MainThread]: An error was encountered while trying to flush usage events
